name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Cache Pip
        id: cache-pip
        uses: actions/cache@v3
        with:
          path: ~/.cache
          key: venv-${{ runner.os }}-${{ hashFiles('*requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install . -r test-requirements.txt
      - name: Lint with flake8 and black
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 score/
          black score/ --check
      - name: Typecheck with mypy
        run: |
          mypy score/
      - name: Sanity Check
        run: |
          # stop the build if there are Python syntax errors or undefined names
          env CACHE_LOCATION=/tmp python -m score.app
      - name: Test
        run: |
          # stop the build if there are Python syntax errors or undefined names
          py.test score/ -v
      - name: Check pyi
        run: |
          python -m score.notes.data
          git diff --exit-code score/notes || ( \
            echo "Error: Running drizzle-kit generate produced changes. Please run locally and commit changes." && exit 1 \
          )
