name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Cache Pip
        id: cache-pip
        uses: actions/cache@v3
        with:
          path: ~/.cache
          key: venv-${{ runner.os }}-${{ hashFiles('*requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install . -r test-requirements.txt

      - name: Lint with flake8 and black
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 spdx_license_matcher/
          black spdx_license_matcher/ --check
      - name: Typecheck with mypy
        run: |
          mypy spdx_license_matcher/

      - name: Test
        run: |
          # stop the build if there are Python syntax errors or undefined names
          py.test spdx_license_matcher/ -v

      - name: Package
        run: |
          # stop the build if there are Python syntax errors or undefined names
          pip install build
          python -m build
          python -m twine check  dist/*

          python -m venv check-venv

          ./check-venv/bin/pip install dist/*.whl
          ./check-venv/bin/spdx-match --help
